### ISSUE TITLE
呀哈哈位置存在一处错误

### ISSUE THREAD

**Issue by BroKun** [lvisei/li-zelda-assets#13]
### 复现步骤：

1. 选择显示呀哈哈
2. 缩小地图，就可以看到有一处呀哈哈标记在地图范围之外
### 其他：
[使用链接](https://locationinsight.antv.antgroup.com/#/app/30dd22f0-99a4-4ae2-8858-91b00e7bbe87?type=case)
![image](https://github.com/lvisei/li-zelda-assets/assets/11978904/b6929b4a-2dd6-48d8-bcf5-35eb7af32a86)

**Comment by heiyexing** [comment]
已修复，今天发版
